# valid
POST http://localhost:8080/customers
Content-Type: application/json

{"firstName": "Fake", "lastName": "Person", "email": "valid@fake.com"}

###

# missing first name
POST http://localhost:8080/customers
Content-Type: application/json

{"lastName": "Person", "email": "valid@fake.com"}

###

# missing last name
POST http://localhost:8080/customers
Content-Type: application/json

{"firstName": "Fake", "email": "valid@fake.com"}

###

# missing email
POST http://localhost:8080/customers
Content-Type: application/json

{"firstName": "Fake", "lastName": "Person"}

###

# first name and last name too short, email invalid
POST http://localhost:8080/customers
Content-Type: application/json

{"firstName": "Fa", "lastName": "Pe", "email": "invalid.com"}

###

# empty object
POST http://localhost:8080/customers
Content-Type: application/json

{}
